version: '2'


services:
    web:
      build:
        context: .
        args:
          http_proxy: "${http_proxy}"
          https_proxy: "${https_proxy}"
      command: python manage.py runserver 127.0.0.1:8000
      volumes:
        - .:/app
        - static_volume:/app/static  # static content
      ports:
        - 127.0.0.1:8000:8000
      container_name: djproject-app

volumes:
  static_volume: